export default function handler(req, res) {
  const quotes = [
    "It's not about motivation; it's about discipline.",
    "Get after it, every damn day.",
    "Your mind quits before your body.",
    "Embrace the suck.",
    "The only way to grow is to suffer.",
    "Be uncommon among uncommon people.",
    "Stay hard.",
    "Take souls.",
    "You have to be willing to suffer to become great.",
    "Get comfortable with being uncomfortable.",
    "Pain unlocks a secret doorway in the mind.",
    "Suffering is the true test of life.",
    "Most people give up at 40%. You gotta be willing to push to 100%.",
    "Don't stop when you're tired, stop when you're done.",
    "Life is one big mind game. Master your mind.",
    "You don't get better on the days when you feel like going, you get better on the days when you don't want to go but you go anyway.",
    "The only person you need to be better than is the person you were yesterday.",
    "Don't let your mind control you. Control your mind.",
    "Success is based on your willingness to stay in the uncomfortable zone.",
    "There is no finish line.",
    "We live in a world where mediocrity is often rewarded.",
    "Be the person who decided to go for it.",
    "Prove yourself to yourself, not to others.",
    "Do what you can't.",
    "The most powerful weapon on earth is the human soul on fire.",
    "Be driven with purpose.",
    "Don't wait for opportunity, create it.",
    "There's no such thing as bad weather, just soft people.",
    "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
    "Motivation is crap. Motivation comes and goes. When you're driven, whatever is in front of you will get destroyed.",
    "You have to build calluses on your brain just like how you build calluses on your hands. Callus your mind through pain and suffering.",
    "When you think that you are done, you're only 40% in to what your body's capable of doing. That's just the limits that we put on ourselves.",
    "The only way you're ever going to get to the other side of this journey is you have got to suffer, to grow.",
    "Greatness pulls mediocrity into the mud. Get out there and get after it.",
    "At the end of the day, hard work may not be enough. You still may fail. But you keep going out there and go after it.",
    "Life is one big tug of war between mediocrity and trying to find your best self.",
    "Life isn't always about doing the things we like to do. It's about doing the things we have to do.",
    "There's no better way to grow than forcing yourself into discomfort.",
    "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'",
    "Nobody cares what you did yesterday, what have you done today to better yourself?",
    "Don't let your surroundings dictate your success.",
    "It's so easy to be great nowadays because everyone else is weak.",
    "If you can get through doing things that you hate to do, on the other side is greatness.",
    "The mind is the most powerful thing in the world. The mind has capabilities that are so unknown, and being able to tap into that is on the other side of suffering.",
    "Every morning in our lives, we have a choice to make. You have the choice to stay in bed and say 'Forget it, I'm not going to work out today.' Or 'Forget it, I'm not going to work hard today.' That's your choice that you gotta make every single day.",
    "You are in danger of living a life so comfortable and soft, that you will die without ever realizing your true potential.",
    "You gotta start your journey. It may suck, but eventually you will come out the other side on top.",
    "The path to success will leave you callused, bruised, and very tired. But will also leave you empowered.",
    "What you do in the dark, when no one is watching, is what makes the difference.",
    "Do not give up, do not tap out, do not say, 'I'm done.' No. You get up and you fight.",
  ];
  res.status(200).json({ quotes });
}
